---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: dev
spec:
  encryptedData:
    DATABASE_URL: AgAyRTHeBb1BE6RoiJHPx7bvY93Eu2RgZBnn3XFX2irR1cvcAqXP6otDRk7qs/qVWC7EHtgVBmagT/T9EZngKUeqJzciQ6bhSxNpvCNxasOpJoSB3OQka1vl+UItpe8won9xw7Hh96JiP2idM4gSEVqqBb8JKoJULrNd32fbGYXywp8nRZ68346bboodCIySLXejeg4fqpY8J/SbelHmJfT+JMOAs1tKrNFRO2XBoXYCLIyFUDLgSZ76tte/oNn+w0aiv0WspGmO/ZctsMQb76uMt1VuqvknWHuguCKQwcqweX8iTmlYBRFc/8WDbMaI8iCaBqZA1fRDY5ouFUa8Z0Yjr7a9LT1ViSNf8NIR1m9hjvgduDaTfjuCaXyLxuE+jJ9O+AhkUVlFu4FfMgBBpn9hsIN/huBj4uABke6JX7F4meLUbKFQEuXgIN5zM8wp+xW64ncqihY6ljKEKzq377ZZtBA2LyCCHJQhmvt6suSHkSi86ObiqJcttOnaLaNcxMssMvLmG47OZgTFb5mUBCDPPINnGaziL+MigB9ShHcAqmWxtgov9x+kjFwrbMrJttPX8MPIg9QZSEPe4uuatrjjykL7mH3NUAEaaF4huHRNP6FFoadHI4X1GaB6MRJPeTrwJ28MY6Wz+tVOio4isqvyV8XFi01xTW0gZDkbmUNOgHPyHV/G0UzzE97homCgnnyO9MEys7nfjxYmkoS/7Ma4lg6IX0k7giO3G/AQ8oalwzQh3Wf/poiX
  template:
    metadata:
      name: postgres-secret
      namespace: dev
