---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-dot-net-secret
  namespace: dev
spec:
  encryptedData:
    DATABASE_URL: AgAONb1m6l9/f1do6ockYb4GIfv4eYnnGnAPsPjmMGGlcgO/OlvO8Ei8xQJNNxGEa3xmTmveYg2dCfrvSEVIDXDanFTL/dOL8suOmI+7wMVzpr13fPwPBuX8y+Xx31N4KrEB0kkQfu/CHdLsse71OAHt9j1boN4lZGcQO9bdtBcGZMZZajo99XWhWielpOqE9Qq88Vpx7Cy5f4/LENpcVLnZMfoJE6X5hT85t1/hWBZzg4GYJONwvdBX9CdD9317akJcbjjpcBQ/6wIJfjJSe1HIc7n9eXv9A0063wCrxc4579dxmEErxxvhUwsidPYGVsRmU8Jdp034lQc8q5YhDVH41jQsB/6e7qPOxi5qH2KFIZg3MN/noeD8tQiSweehQFMacrGwUjcCaWSCyLUXRdiF1VaQGmBfoGznFhSkL/0kB7xrsxCwKAq6pEOwdX87nPbkXEzWOxIZTP5fZiQahL22PPNUWW4BhhiYLrAPFMryD71sLIxI+LMwMcvWRwlEBGx0gCtuA9baIs2TfHjiY7g/PWSaF+dy4dsM4U3GG9rAcdgWpzP6ZBidVB0fVEeoNr/idgHkLifQF5gOlUzioMHWdSJudtfYk9irE/+E4GseQv0YauempyMNotnIioP7mzvaumZMZzTkdlGwLaFT10GImNzdWZmEVTo7/c1XVcHp7semYXkHKWSMqqGknDlyXXeVCCSDUdlBgte9SPR7E7DP0VGYNP9tmTmHlo9G0iDt1WnpvcJ+n8qsy08FTS1i1hWp/QcPMBdJOAEDHUJghNMZ
  template:
    metadata:
      name: postgres-dot-net-secret
      namespace: dev
