---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-dot-net-secret
  namespace: prod
spec:
  encryptedData:
    DATABASE_URL: AgCXlyN4MKd7kNGGeHXVixJZcKZqsV5T3KX5Rw5cW7b34zL+GcTIWWKzCP3dRVqf7TYhoXMyapTZC1WB7vJuuHgYOTz72D+Bk9Qa6oSmZKEB4FKpvVp47k3HENOeImFLrfhH+LVEknbAtprcvCv9Nn6MEHa5F4aB1q6KW/p/8nVwgC5LriyEVcKahkctmKvSvEMgWygSQEnhxqgqStN+YefgD2gWMFcJ5BD/fJBXYNmqzJP1/SqzghjY47fxdYHU9dUMnkSVEks3yi5SXo6M6tzBNqMrbRN+l4nXr9w00je1AuVWxwqp8V+pGRpWJVCAiwc8xLO03WvmAxeei9ULKzHNZe3F5Olb3p6lwE6N5C1pyArQ20o0GyCWdn1RmjWWFi1ZvRFqG8ojPWSh2frJlkofIGddI3CizDkLYvduwTmKwae3NrQdVF1N9e5zR0aW/VqFzRDAxnDBr+/mrls2MueDjc8lHLRFMVTB0NJ82I4UTFkDR24mWyyadbwxGdrTMnMXZtODCEJEJ6JcgscK4ynbuqcsEHAOt/Ee2qym1J50LbtZqsQQgMTPw+AJQfFmBZVsby2WruUCOhObxR210FG+SuJ7gWoKap3irXdJ38Y70Aj7DCP0hUXTvJ9lHjnOlQeMR3TjwoZP4XMR72aTrMg3mplCCYnNjtvWrqByHZfwtCVdW6ozv73Vc9TX2EQHiU3toFJfsWI6Kf//Tw1S3uxLv9eG+QuzMRSS+mg2m0uqt/qaE3pD3r7UvGUEMMrJGF3cvmU8BVVXPrYVPHO0/qdg
  template:
    metadata:
      name: postgres-dot-net-secret
      namespace: prod
