---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: prod
spec:
  encryptedData:
    DATABASE_URL: AgDAP6h9OnSfb/aGVBsi4sr2qF1W5DUFQZ9f2+JyPl00wiQpcITCOOL3r66CkISre5VnbuznxW8nW8RXJy7WYPK+r3yMweFm2ueTeXa/mMCos7BjMMFJu1ZB0uRz/ECC7KMcaHCopJx54bP7kXDcIRg47FHLY2AkP5Zs8uUpztLcUQphOYWJ0VsKPO7w+YeIML2LtOxUp0UZQKLA31GjzbJjG57ZuW2qW8NJJX0k3p+Uki5lMKNZtv/ieaPyN6nBvRAP+Lgtiegp6D2jeVkllniIJ6Aeja6ZYvMr0UZIhko3yYv+pMyJzuGvjt81N3BDxDGjTmen+J5ONycncnDVhGUAZ7DAqZWzUGP6Fkny5LI9/BrmzcyuYz5oykXKDWPGOz61zYs2KyDxwvXaAf9dRXtOTwQyCrHcOcQ06GEl+t1S63T4OTQNonqzBdZZmhnuu8GYdvN7BclSMDko3Yhx9Rz3jtFzoynFfFcfbjjQ9YVZfQANWOg17CEEmNoLFu59GjTqYQiTmZr1C9pY+9NvjHT6IyWjkZCzuiHzATIZ7FKOa5NSdcK3Nf/AEDALq6OJQrF7IsbK5ZDdBE3h1nnY9NOAV7bPWJ2W1OZZnBlDpkBpnxRUFl3d+wiZe0v9Oq4BM5v1eaVZ8l5TGZgJO1mVkLJQoAj0OJWEz7umpVwMfE1gHxHH5Tv18lnHE3Xf2Um9+VS+F4GS8P3rEt3zbgjy+iWnLS2BPEA5I7Zsk9ucAG4xeqqYLXW1/sSQ
  template:
    metadata:
      name: postgres-secret
      namespace: prod
